### ISSUE TITLE
Django 1.9

### ISSUE THREAD

**Issue by henriquechehad** [mwolff44/yawd-admin#3]
There are many changes? 

What needs to be implemented and be compatible with Django 1.9.X ?

**Comment by mwolff44** [comment]
Yes, there some changes that need to be tested. But i want also to add bootstrap 3 support as bootstrap 2 is EOL.
You can propose pull request, i will be happy to integrate it.

**Comment by henriquechehad** [comment]
@mwolff44 I started the Django 1.9.x support, check:

https://github.com/mwolff44/yawd-admin/compare/master...henriquechehad:django1.9.5?expand=1

**Comment by mwolff44** [comment]
thanks for your great job. I have integrated it
